In [171]:
import ROOT
import math
# Colors
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.ticker import AutoMinorLocator, MultipleLocator
from root_numpy import root2array, tree2array
from root_numpy import testdata, fill_hist
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, Dropout
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (recall_score,  precision_score, f1_score, roc_auc_score,
                             make_scorer, confusion_matrix, accuracy_score)

## Import ROOT file

You can either import a file which includes both Xtohh1000 and Xtohh2000 signal events, but their samples must be different or import just the file which includes one of the signals and the background.

In [2]:
rfile = ROOT.TFile("/home/andrea/Escritorio/CERN data/Try3/all_1000.root")
intree = rfile.Get("Nominal")
array = tree2array(intree)
df = pd.DataFrame(array)
df = df[df['sample'] != 'data']
df.columns.values

array(['sample', 'EventWeight', 'EventNumber', 'm_region',
       'm_FJNbtagJets', 'm_FJpt', 'm_FJeta', 'm_FJphi', 'm_FJm', 'm_DTpt',
       'm_DTeta', 'm_DTphi', 'm_DTm', 'm_dPhiFTwDT', 'm_dRFJwDT',
       'm_dPhiDTwMET', 'm_MET', 'm_hhm', 'm_bbttpt'], dtype=object)

## Identifying signal and background

If the row sample is 'Xtohh1000' or 'Xtohh2000', then the new columns will have a 1 in this row.

In [3]:
def classifier(row):
    if row['sample'] == 'Xtohh1000':
        return 1
    #else if row['sample'] == 'Xtohh2000':
    #    return 1
    else:
        return 0

In [4]:
# Select rows different of data samples
# Select rows on the SR_1tag region
df = df[(df['sample']!='data') & (df['m_region']=='SR_1tag')]
df["signal"] = df.apply(classifier, axis=1)

# Delete columns
not_cons = ['sample', 'EventWeight', 'EventNumber', 'm_region', 'm_FJNbtagJets', 'm_FJphi', 'm_FJeta', 'm_DTeta', 'm_DTphi']
df.drop(not_cons, axis=1, inplace=True)
df

m_FJpt          m_FJm       m_DTpt          m_DTm  m_dPhiFTwDT  \
157      371.481293   10326.322266   514.951416  165099.500000     3.040748   
159      671.963440    6808.773926   648.846802  165977.250000     3.086895   
349      468.992157   16738.765625   436.591125   85872.664062     3.135852   
383      460.490295   25541.880859   344.878723  131553.406250     2.889410   
385      549.088257   45904.292969   506.746826   95809.492188     3.103930   
419      567.861572   32648.080078   552.612671  139901.515625     3.104266   
503      528.577332   15937.913086   437.923706  185447.890625     3.086575   
619      494.375610   23339.521484   448.691528  147805.500000     3.131119   
661      478.946838  140186.984375   583.283447  169675.593750     2.974471   
665      526.373291  165002.656250   379.679871  152255.546875     2.933894   
669      483.061340   14511.416016   486.490814  111994.109375     3.112489   
697      452.788513   27771.720703   344.960480   89454.156250     2.864760   
901      839.546082  107527.265625   782.154785  132845.484375     3.133904   
909      559.198425   79346.945312   543.565186  105745.164062     3.129049   
951      482.199341  148108.765625   436.245697  142115.859375     3.049194   
989      558.163208   23126.580078   506.990417  122268.382812     2.812290   
1033     450.726868   36628.386719   386.686188  138375.812500     3.116008   
1119    1152.954102  352830.000000  1093.103760  179367.484375     3.116892   
1181     521.438110   38289.187500   355.886475   64518.648438     2.995710   
1215     510.587708  161047.187500   406.966400  170610.250000     2.884973   
1249     363.197845   15284.554688   448.225983  108848.593750     3.092423   
1277     651.103210   58642.300781   741.715393  157329.453125     3.114610   
1285     472.558319   18946.101562   424.734711   88455.882812     2.965675   
1389     322.705383   46365.648438   474.272278  179494.890625     2.352673   
1411     628.412659  100667.460938   549.556641  111455.109375     2.794979   
1461     582.435242   17034.523438   534.251160  135212.328125     3.135126   
1511     933.542725  221648.843750   877.118530  206660.171875     2.976413   
1553     476.918976   12582.181641   451.254486   72892.140625     3.130724   
1573     463.709076  164338.234375   415.633698  165069.515625     3.079272   
1619     603.524353  120309.312500   641.197205  153710.593750     3.101515   
...             ...            ...          ...            ...          ...   
255407   561.373901   91061.343750   394.545410  136163.812500     3.136078   
255489   538.204956   67471.445312   447.335938  169174.484375     1.409512   
255497   411.691254  131675.312500   623.853577  147143.703125     2.995242   
255501   997.008118  285989.781250   751.856873  174247.578125     2.954057   
255517   545.570984  128193.304688   372.957397  117044.578125     3.010453   
255531   464.922028   21961.996094   359.453156  126890.585938     3.012895   
255559   531.843445   95508.140625   502.055481  172054.968750     3.112240   
255599   400.024109   88987.757812   480.967987   88336.367188     3.055225   
255609   624.391785  115030.500000   372.942749  102008.351562     3.038617   
255621   743.645142  371418.968750   682.603638  297794.406250     3.071952   
255627   870.085327  249184.390625   762.416260  168062.390625     3.035105   
255635   337.309479  116750.015625   457.679901  104442.492188     3.081994   
255639   495.807465   36086.218750   522.075928  165792.687500     3.096951   
255651   557.871826   94863.304688   534.551636  134872.453125     2.984610   
255671   490.118896   46554.863281   350.744019  117199.093750     2.823932   
255693   521.865540   30628.832031   370.622406  122254.695312     3.045167   
255709   616.131775   35922.226562   636.514526  147446.328125     2.544024   
255717   562.805054  120686.468750   427.312836  103163.250000     3.097503   
255719   572.113831   18611.822266   373.004578  118345.804688 

## Dividing data for training and testing

In [132]:
# Features
feature_cols = df.columns.values[:-1]

X = df.loc[:, feature_cols].values
# Targets
y = df['signal'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X_train.size 

102520

## Configure neural network

In [172]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(15, activation='relu', kernel_initializer='uniform', input_dim=10))
#Second  Hidden Layer
classifier.add(Dense(15, activation='relu', kernel_initializer='uniform'))
#Third  Hidden Layer
classifier.add(Dense(15, activation='relu', kernel_initializer='uniform'))
#Output Layer
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='uniform'))

In [173]:
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])

In [189]:
#Fitting the data to the training dataset
classifier.fit(X_train,y_train, batch_size=50, epochs=50)

Epoch 1/50
10252/10252 [==============================] - 1s 69us/step - loss: 0.4733 - acc: 0.7538
Epoch 2/50
10252/10252 [==============================] - 1s 83us/step - loss: 0.4870 - acc: 0.7339
Epoch 3/50
10252/10252 [==============================] - 1s 84us/step - loss: 0.4789 - acc: 0.7464
Epoch 4/50
10252/10252 [==============================] - 1s 94us/step - loss: 0.4766 - acc: 0.7520
Epoch 5/50
10252/10252 [==============================] - 1s 90us/step - loss: 0.4779 - acc: 0.7485
Epoch 6/50
10252/10252 [==============================] - 1s 81us/step - loss: 0.4720 - acc: 0.7549
Epoch 7/50
10252/10252 [==============================] - 1s 86us/step - loss: 0.4827 - acc: 0.7426
Epoch 8/50
10252/10252 [==============================] - 1s 80us/step - loss: 0.4886 - acc: 0.7336
Epoch 9/50
10252/10252 [==============================] - 1s 80us/step - loss: 0.4708 - acc: 0.7583
Epoch 10/50
10252/10252 [==============================] - 1s 76us/step - loss: 0.4695 - acc: 0.7611

In [190]:
eval_model=classifier.evaluate(X_train, y_train)
eval_model

10252/10252 [==============================] - 1s 125us/step


[0.44606970313397226, 0.789992196667813]

In [191]:
y_pred=classifier.predict(X_test)
y_pred =(y_pred>0.5)

In [192]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1623  215]
 [ 343  382]]


In [193]:
r = recall_score(y_test,y_pred)
p = precision_score(y_test,y_pred)
a = accuracy_score(y_test,y_pred)

print("recall:", r)
print("precision:", p)
print("accuracy:", a)

recall: 0.526896551724138
precision: 0.6398659966499163
accuracy: 0.7822863831447523


In [203]:
y_test[:20]

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0])

In [202]:
y_pred[:20]

array([[False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False]])